### ISSUE TITLE
Random error during nothing being occuring

### ISSUE THREAD

**Issue by Barbatos-Rex** [LukWebsForge/HasteIt#13]
While i was programing a random class this error popped up and since then it has constantly appearing! BTW nice plugin, easy to use and quite useful. Anyway, the error is the following:
java.lang.Throwable: cannot share data context between Swing events; initial event count = 102167; current event count = 102353
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:345)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:55)
	at com.intellij.openapi.actionSystem.AnActionEvent.getData(AnActionEvent.java:184)
	at com.intellij.openapi.actionSystem.AnActionEvent.getProject(AnActionEvent.java:141)
	at de.lukweb.discordbeam.DiscordMenu.uploadText(DiscordMenu.java:64)
	at de.lukweb.share.ShareMenu.actionPerformed(ShareMenu.java:96)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:604)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:657)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:656)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:472)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:830)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:775)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Hope it can help to fix further bugs.

**Comment by lukbukkit** [comment]
Thanks for your bug report. I've got three questions for you to determine the impact of this issue more exactly.
1. Which version of HasteIt are you using?
2. Do you have DiscordBeam installed?
3. Which IntelliJ version are you using?

**Comment by Barbatos-Rex** [comment]
1. I don't have that plugin installed in my computer;
2.Yes i have.
3.Intellij 2013.3.1

**Comment by lukbukkit** [comment]
Thanks for your answers.
One thing confuses me, did you mean the IntelliJ version `2019.3.1`, because DiscordBeam doesn't support versions below `2018.3`.

Anyway I did a bit of research and I guess I fixed the problem. Here's a new build of DiscordBeam (supports all IDEA versions starting from `2019.3`): [DiscordBeam-1.05.zip](https://github.com/LukWebsForge/ShareIt/files/4410083/DiscordBeam-1.05.zip)
Just drop the zip file into your IDE and the plugin will be automatically updated. If the error still appears please add a comment to this issue 👍

**Comment by lukbukkit** [comment]
If this error occurs once more, please open a new issue. Thanks for your help.
